andsens/homeshick

- bin/homeshick
- bin/homeshick.csh
- homeshick.fish
- homeshick.sh
- test/helper.bash
- test/suites/homeshick_dir.bats
The current implementation of homeshick contains hard-coded paths to the (default) installation location. This patch makes homeshick position-independent by allowing the user to specify an alternative installation location using the `HOMESHICK_DIR` environment variable.
> HOMESHICK_DIR defines location of homeshick

- test/helper.bash
- test/suites/abs_path.bats
- test/suites/git_url_basename.bats
This allows running detached tests (i.e., the test cases do not have to
be co-located with the homeshick instance under test), like this:
$ HOMESHICK_DIR=/usr/share/homeshick bats test/suites/
This PR is a follow-up to #138.
> Tests also have to observe HOMESHICK_DIR.

- README.md
update quick install for csh homeshick alias to include trailing newline when appending to .cshrc
because there is a long standing issue in csh and tcsh
that skips execution of last line in script if it does NOT end with newline
> update quick install for csh homeshick alias to include trailing newline when appending to .cshrc

- completions/homeshick.fish
Use sed instead of expr, because there is no substr in expr on OSX.
> Fix fish completions on OSX

- homeshick.sh
Hello,
I have written a simple script to update my castles, whose interpreter is /bin/sh. On most of my systems it was working fine, until I've tried Ubuntu where dash is used. There, when I am sourcing `homeshick.sh` in dash, I get this error:
```
6: /home/joko/.homesick/repos/homeshick/homeshick.sh: Syntax error: "(" unexpected
```
This commit fixes this error. I have tried it over bash and zsh successfully, as well, and it passed the testsuites.
> Make homeshick() dash-compatible

- lib/commands/pull.sh
A change in pull.sh has a debug line that probably shouldn't be there. It outputs a spurious "1" when pulling:
<pre>
fire@danton:~ $ homeshick pull vim
pull vim
1
updates The castle vim has new files.
symlink? [yN] y
symlink .vim/bundle/vim-git
</pre>
> Remove debug output from pull.sh

- lib/commands/check.sh
Turns out git 1.7... (1) doesn't support the -q option to ls-remote, and (2) is what ships with RHEL 6/CentOS 6, so `homeshick check` always fails `uncheckable` there. As best as I can tell, -q is a noop for 'git ls-remote --heads' when you supply the repo as an argument, so it's safe to remove.
> Make 'homeshick check' ls-remote call compatbile with git-1.7

- .travis.yml
The problem was bats, as Debian package sources were mixed with those of Ubuntu because of a missing bats package in Ubuntu. That doesn't work. The issue is fixed by installing bats from source.
Since Ubuntu uses comparatively old versions of packages, fish is added in as a Launchpad repo. This way, the newest fish version is tested.
csh is another interesting bit. On most Unix systems (except Linux) csh is replaced/symlinked to tcsh by default and on Linux actually creates a csh symlink when installing tcsh. This is the one you want, as plain csh is horribly incompatible with practically everything and won't work with the testing script. tcsh does.
I also added some spacing between the sections.
Also interesting: http://www.faqs.org/faqs/unix-faq/shell/csh-whynot/
> Make Travis build with bats, csh and fish

- homeshick.fish
It appears to be a fish issue (https://github.com/fish-shell/fish-shell/issues/3708), which is worked around by adding `(string escape -- $argv)` instead of `$argv`.
Fixes #170, moved to correct branch from #171.
> Fix fish path resolution for paths with spaces

- homeshick.fish
- test/suites/misc.bats
Hi,
just noticed a small bug in the fish wrapper, which causes it to print error message when invoked without arguments. This PR adds an unit test, and fixes the issue.
Thanks for this cool project BTW!
> Fix argument testing in homeshick.fish

- README.md
The `git://` protocol is considered insecure and deprecated, so switching to `https://` is a good idea. This also capitalizes Bash and Git (which are the official casings used by those projects).
> Use HTTPS for Git clone operations in README

- bin/homeshick
- lib/commands/refresh.sh
- lib/fs.sh
Replace common shell utilities with built-in bash functions to speed
up execution. Also replace call to "date" with T_START that is set when
homeshick first starts.
This speeds up a no-op "homeshick refresh" with 10 castles from 290ms
to 200ms (~31% improvement) on my machine by reducing calls to exec.
> Speed up refresh operation by reducing exec calls

- bin/homeshick
- completions/_homeshick
- completions/homeshick-completion.bash
- lib/commands/help.sh
First of all, thanks - homeshick is great software.
I frequently try to list the available castles using `homeshick ls`
instead of `homeshick list`. I fixed this in my own `.zshrc` but figured
this might be a common typo, so I implemented it in homeshick.
Figured I'd see if this change is welcome.
> Alias "list" to "ls"

- homeshick.fish
This change makes homeshick.fish find homeshick if it is on the path, without needing to set HOMESHICK_DIR.
(Homebrew installs homeshick on the path, and also
installs homeshick.fish into a function autoloading directory.)
> Make homebrew homeshick work seamlessly with fish

- lib/commands/check.sh
This is necessary to allow `git ls-remote` to pick up repository-specific information, such as values for core.sshCommand or http.userAgent that are stored in the repository's .git/config file.
I'm not sure how best to add coverage for this in the test suites, as all the configuration options that seem relevant to me are ones that require a remote server. Setting up a temporary local HTTP or SSH server as part of the test suites seems like overkill for what is – in my opinion – a very safe change.
I've also not actually managed to run the test suites either. I tried to follow the guide at https://github.com/andsens/homeshick/wiki/Testing, but then running `test/run` seems to have the test suite return success immediately, even when I deliberately broke a test, while running …
> cd to a repo before running git ls-remote

- lib/commands/clone.sh
For consistency with other uses of `cd`, make following commands
conditional on the `cd` command completing successfully when
initializing submodules as part of a clone, rather than assuming it will
complete successfully and carrying on regardless.
> Don't assume changing directory will work

- lib/commands/check.sh
Now that `git ls-remote` is run from within a repo, we can refer to the
remote by name, rather than needing to specify the URL.  Do that, in the
name of simplifying the code and removing the need to worry about URLs
at all during `homeshick check`.
> Remove need for getting URL for ls-remote

- homeshick.fish
With a recent system update, type -P in fish shell started printing an error message in case no homeshick binary exists on PATH. This is an expected condition in the homeshick fish wrapper and therefore the error message should probably not reach the user.
> Silence homeshick binary finding in fish shell

- bin/homeshick
Doing a "homeshick ls" would throw an error like this:
/home/martin/.homesick/repos/homeshick/bin/homeshick: line 163: /home/martin/.homesick/repos/homeshick/lib/commands/ls.sh: No such file or directory
/home/martin/.homesick/repos/homeshick/bin/homeshick: line 167: list: command not found
"ls" is an alias to "list". Follow what is done for the other aliases
and just source the right command explicitly.
Fixes: 387df51b6314 (Alias "ls" to "list" command)
> Fix ls aliasing

- test/helper.sh
This fixes the test cases that started failing with Git 2.38.1:
* https://github.com/git/git/blob/master/Documentation/RelNotes/2.38.1.txt
* https://github.com/git/git/blob/master/Documentation/RelNotes/2.30.6.txt
It also supresses the annoying message about the default branch name.
> add a default .gitconfig file to the test harness

- .github/workflows/test.yaml
- test/.gitignore
- test/get_bats_libs.sh
- test/helper.sh
It used to be that homeshick could be tested just by cloning the repository and running `bats test/suites`. Unfortunately, since the introduction of the 3 bats libraries, this is no longer the case.
[The wiki](https://github.com/andsens/homeshick/wiki/Testing) specifies how the test dependencies should be installed to make it work, but there are some disadvantages to this approach:
* Root access is required to install the dependencies under `/usr/local/`.
* The process of setting up a development environment (locally) is cumbersome.
With this PR, I propose turning the bats dependencies into Git submodules of homeshick itself. This is also [the approach suggested by the bats-core developers.](https://bats-core.readthedocs.io/en/stable/tutorial.html) The advantages of this are:
* Anyone …
> Provide test dependencies as submodules

- .editorconfig
According to the [Contribution guidelines](https://github.com/andsens/homeshick/blob/master/CONTRIBUTING.md), shell scripts should be indented by 2 spaces, so make the `.editorconfig` match that.
> editorconfig: match documented code style

- lib/commands/link.sh
The link command ignores castles without a `home` directory, and logs a message about it.
I think this messages should only be shown when verbose output is enabled, similar to the treatment of files whose links remain unchanged. This also matches the *no news is good news* principle most Unix programs operate by, where no output means it either did nothing, or exactly what you asked for.
> link: only log ignored castles with verbose

- lib/commands/help.sh
- lib/commands/refresh.sh
- lib/prompt.sh
- test/suites/refresh.bats
While being a great tool, `homeshick` can be a bit awkward when used in an automated fashion. Its `--batch` mode means "pick the (safe) default option" for every user prompt, which has the unfortunate effect of making most commands rather impotent when run in batch mode.
Because of this, I currently have to write `echo 'y' | homeshick refresh` to automate the updating of all castles at regular intervals, which is a bit corny. I'd much prefer to just write `homeshick --batch refresh`.
In this pull-request, I propose a way to achieve that by allowing commands to change the default prompt response when running in batch mode. The initial application is the *refresh* command.
This implies changing the meaning of `--batch` mode to be "just do what's expected without bothering me" in order to …
> refresh: batch mode also pulls by default

- test/run
The previous code was actually getting the exit code of `!`, which is always 0 inside the if statement.
> Set the exit code correctly in `test/run` when tests fail

- bin/homeshick
- lib/commands/pull.sh
- test/fixtures/pull-renamed.sh
- test/fixtures/pull-test.sh
- test/suites/pull.bats
This PR reworks the way `pull` checks for new files for symlinking, which was broken before due to a missing `$` in front of the arithmetic expansion. This made it resolve to HEAD instead of HEAD@{1.seconds.ago}.
It now creates a temporary tag in each castle before running git pull, and diffs against that in symlink_new_files. It also wasn't checking for renamed files, but that's easily fixed with `--diff-filter=AR`.
This should be much more robust than the previous time-based method, which broke intermittently in my local tests and once during actual use. If `$now == $T_START` and the current second increments between `$now` and the git diff call, then HEAD@{1.seconds.ago} will point to the pull itself rather than the commit before it.
I've also added a whole bunch of tests covering all …
> Fix pull not symlinking new and renamed files

- bin/homeshick
- lib/commands/pull.sh
- test/suites/pull.bats
As seen in #225, this approach was more complicated than it needed to be and caused confusion for users.
> Don't use git tags in pull
